"""add stock_minimum

Revision ID: 07a20ee428a1
Revises: 
Create Date: 2026-06-01 20:20:02.821895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07a20ee428a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stok_minimum', sa.Float(), server_default='0', nullable=False))
        batch_op.drop_column('harga_jual')
        batch_op.drop_column('harga_beli')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('harga_beli', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('harga_jual', sa.INTEGER(), nullable=True))
        batch_op.drop_column('stok_minimum')

    # ### end Alembic commands ###
