"""add database penjualan

Revision ID: 218f0a5d1727
Revises: 2f649efdab8b
Create Date: 2026-05-25 11:40:00.350897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '218f0a5d1727'
down_revision = '2f649efdab8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('penjualan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=False),
    sa.Column('catatan', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_penjualan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('penjualan_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['penjualan_id'], ['penjualan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_penjualan')
    op.drop_table('penjualan')
    # ### end Alembic commands ###
