"""tabel versi 1

Revision ID: c3d9c3c9d3dd
Revises: 
Create Date: 2026-05-16 15:11:41.134214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3d9c3c9d3dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode_barang', sa.String(length=32), nullable=False),
    sa.Column('nama_barang', sa.String(length=100), nullable=False),
    sa.Column('kategori', sa.String(length=64), nullable=False),
    sa.Column('satuan', sa.String(length=32), nullable=True),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('harga_beli', sa.Integer(), nullable=True),
    sa.Column('harga_jual', sa.Integer(), nullable=True),
    sa.Column('keterangan', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode_barang')
    )
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_menu', sa.String(length=100), nullable=False),
    sa.Column('harga', sa.Integer(), nullable=False),
    sa.Column('deskripsi', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('jumlah', sa.Float(), nullable=False),
    sa.Column('satuan', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe')
    op.drop_table('user')
    op.drop_table('menu')
    op.drop_table('inventory')
    # ### end Alembic commands ###
