"""remove input satuan recipe

Revision ID: fcec36657e79
Revises: 07a20ee428a1
Create Date: 2026-06-01 21:04:54.195321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcec36657e79'
down_revision = '07a20ee428a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('satuan')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('satuan', sa.VARCHAR(length=32), nullable=True))

    # ### end Alembic commands ###
